PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX html: <http://tools.ietf.org/html/>

SELECT ?o

WHERE {

#<http://purl.obolibrary.org/obo/ENVO_03000056> <http://purl.obolibrary.org/obo/RO_0002233> ?o .

<http://purl.obolibrary.org/obo/ENVO_03000056> rdfs:subClassOf{,10} ?o .

} 
