PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX html: <http://tools.ietf.org/html/>

SELECT DISTINCT ?participant ?property ?value 

WHERE { 
?participant rdfs:subClassOf ?node .
?node rdf:type owl:Restriction .
?node owl:onProperty ?property . 

{
#direct case
?node owl:someValuesFrom ?value .
?value rdfs:label ?label .
}

UNION 

{
#union class case:
?node owl:someValuesFrom ?v .
?v owl:unionOf/rdf:rest*/rdf:first ?value .
}

VALUES(?property){
(<http://purl.obolibrary.org/obo/RO_0002233>)
(<http://purl.obolibrary.org/obo/RO_0002234>)
}

VALUES(?participant){
(<http://purl.obolibrary.org/obo/ENVO_03000056>)
(<http://purl.obolibrary.org/obo/ENVO_03000103>)
(<http://purl.obolibrary.org/obo/ENVO_03000047>)
}

}
