PREFIX file: <file:/home/kai/Desktop/grad_school/marmic/master_thesis/kblumberg_masters_thesis/testing/test_basic.csv> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ietf: <http://tools.ietf.org/html/>

SELECT ?s ?v

FROM <test_basic.nt>

WHERE 
{

?label <http://www.w3.org/2000/01/rdf-schema#label> "Nitrate" .

?s ?label ?v

}
