PREFIX file: <file:/home/kai/Desktop/grad_school/marmic/master_thesis/kblumberg_masters_thesis/testing/test_basic.csv> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ietf: <http://tools.ietf.org/html/>

SELECT ?s ?p1 ?o

FROM <test_basic.nt>
FROM <test_basic_supplemental.ttl>

WHERE 
{

?s ?p <http://purl.obolibrary.org/obo/CHEBI_17632> .

?s ?p1 ?o .

#<http://purl.obolibrary.org/obo/CHEBI_17632> ?p ?o .


#?label <http://www.w3.org/2000/01/rdf-schema#label> "Nitrate" .

#?s ?label ?v

}
