PREFIX file: <file:/home/kai/Desktop/grad_school/marmic/master_thesis/kblumberg_masters_thesis/testing/test_inorganic_chem/test_inorganic_chem_cleaned.csv>
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ietf: <http://tools.ietf.org/html/>

PREFIX spatial:<http://jena.apache.org/spatial#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX gn:<http://www.geonames.org/ontology#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX loticoowl:<http://www.lotico.com/ontology/>


SELECT ?nDep ?nLat ?nDT

FROM <test_inorganic_chem_cleaned.nt>
FROM <test_inorganic_chem_cleaned_sup.ttl>

WHERE 
{

#give me any things that somehow linked to nitrate
?NitrateColumn ?no3link obo:CHEBI_17632 .

#give me something about Latitude
?LatitudeColumn rdfs:label "Latitude" .

#give me something about date time
?DateTimeColumn rdfs:label "Date Time" .

#give me someting about depth
?DepthColumn rdfs:label "Water Depth" .

# give me a data item that is about a marine water body, and get me it's rows. 
?s rdf:type obo:IAO_0000027;
	obo:IAO_0000136 obo:ENVO_00001999 ;
	ietf:rfc4180row ?MarWatBodRows .

#get data which has nitrate information get its nitrate and latitude
?MarWatBodRows ?NitrateColumn ?nData ;
	?LatitudeColumn ?nLat ;
	?DateTimeColumn ?nDT ;
	?DepthColumn ?nDep .

?MarWatBodRows spatial:nearby(79.1338 6.0925 1 'mi').

# filter has to go inside the where clause 
#FILTER( xsd:float(?nLat) >= 79 )

#GRAPH ?graph {}

} 

#GROUP BY ?nDep ?nLat ?nDT
#ORDER BY ?nDep ?nDT
#HAVING(count(?nData) > 10 )







 
  
