PREFIX file: <file:/home/kai/Desktop/grad_school/marmic/master_thesis/kblumberg_masters_thesis/testing/test_inorganic_chem/test_inorganic_chem_cleaned.csv>
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ietf: <http://tools.ietf.org/html/>


SELECT DISTINCT ?data

FROM <test_inorganic_chem_cleaned.nt>
FROM <test_inorganic_chem_cleaned_sup.ttl>

WHERE 
{

# give me a data item that is about a marine water body, and get me it's rows. 
?s rdf:type obo:IAO_0000027;
	obo:IAO_0000136 obo:ENVO_00001999 ;
	ietf:rfc4180row ?MarWatBodRows .

?MarWatBodRows ?has ?stuff .

?has ?no3link obo:CHEBI_17632 .

#give me any things that are linked to nitrate
#in this case any data columns about nitrate
?NitrateColumn ?no3link obo:CHEBI_17632 .

?NitrateColumn ?no3link obo:CHEBI_17632 .

?MarWatBodRows ?NitrateColumn ?data .

}
