PREFIX file: <file:/home/kai/Desktop/grad_school/marmic/master_thesis/kblumberg_masters_thesis/testing/test_inorganic_chem/test_inorganic_chem_cleaned.csv>
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ietf: <http://tools.ietf.org/html/>

SELECT ?nLat 
	(group_concat(?nData; separator=" , ") as ?nitrateData)
	(group_concat(?oData; separator=" , ") as ?oxygenData)

FROM <test_inorganic_chem_cleaned.nt>
FROM <test_inorganic_chem_cleaned_sup.ttl>
FROM <test_phys_oce_current.nt>
FROM <test_phys_oce_current_sup.ttl>

WHERE {

#These function kindof like imports to be able to access the imporant data pieces within my rdf data
#give me any things that somehow linked to nitrate
?NitrateColumn ?no3link obo:CHEBI_17632 .

#give me any things that are somehow linked to oxygen
?OxygenColumn ?o2link obo:CHEBI_15379 .

#give me something about Latitude
?LatitudeColumn rdfs:label "Latitude" .

#give me something about Longitude
?LongitudeColumn rdfs:label "Longitude" .

#give me any things that are somehow linked to oxygen
?OxygenColumn ?o2link obo:CHEBI_15379 .

	{
	# give me a data item that is about a marine water body, and get me it's rows. 
	?s rdf:type obo:IAO_0000027;
		obo:IAO_0000136 obo:ENVO_00001999 ;
		ietf:rfc4180row ?MarWatBodRows .

	#get data which has nitrate information get its nitrate and latitude
	?MarWatBodRows ?NitrateColumn ?nData ;
		?LatitudeColumn ?nLat ;
		?LongitudeColumn ?nLon .

	OPTIONAL {?marCurObj rdf:type obo:IAO_0000027 ;
			obo:IAO_0000136 obo:ENVO_01000067 ;
			obo:OBI_0001620 ?oLat .}
	
	FILTER(xsd:float(?nLat) >= xsd:float(?oLat))
	FILTER(xsd:float(?nLat) <= xsd:float(?oLat))
	}

UNION 

	{
	# give me a data item that is about a marine current, and get me it's rows. 
	?s1 rdf:type obo:IAO_0000027;
		obo:IAO_0000136 obo:ENVO_01000067 ;
		ietf:rfc4180row ?MarCurRows .

	#get data which has oxygen information get its oxygen and latitude
	?MarCurRows ?OxygenColumn ?oData .	
	}
} 
