PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

SELECT ?s ?c ?filterValue
FROM <datastore.ttl>
WHERE {


{
#get me some thing which is a data matrix about seawater
#could put a ?filterValue in place of obo:IAO_0000136 to screen for input values. 
?s rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:first obo:OBCS_0000120 ; 
   rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:rest/rdf:first/owl:onProperty obo:IAO_0000136 ;
   rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:rest/rdf:first/owl:someValuesFrom ?filterValue .#obo:ENVO_00002149 .
   #obo:BFO_0000051 ?c .
} UNION
{
#get me a something (a column) which is part of some data matrix and is about some value, and return me that value
#could put a ?filterValue for ?value to screen for input values. 
?c rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:first/owl:onProperty obo:BFO_0000050 ;
   rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:first/owl:someValuesFrom obo:OBCS_0000120 ;
   rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:rest/rdf:first/owl:onProperty obo:IAO_0000136 ;
   rdf:type/owl:equivalentClass/owl:intersectionOf/rdf:rest/rdf:first/owl:someValuesFrom ?filterValue .
}

VALUES (?filterValue) {
(<http://purl.obolibrary.org/obo/ENVO_00002149>)
(<http://purl.obolibrary.org/obo/ENVO_09200006>)
#(<http://purl.obolibrary.org/obo/PATO_0001595>)
(<http://purl.obolibrary.org/obo/ENVO_01001037>)
}


}
