PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX html: <http://tools.ietf.org/html/>

SELECT ?c ?o

#FROM <ice_algal_chlorophyll.nt>
#FROM <ice_algal_chlorophyll.ttl>

#FROM <first_year_ice.nt>
#FROM <smog_data.nt>

FROM <datastore.ttl>

WHERE {
# give me a data item and get me it's rows. 
?s rdf:type obo:OBCS_0000120 ;
	html:rfc4180row ?DataItemRows .

#get me other data colums from these rows
?DataItemRows ?p ?filter ;
	?c ?o . 

filter (?c != rdf:type && ?o != html:rfc4180Row)
filter (?c != html:rfc4180rowPosition)

#excluding the columns I already know to be about multiyear ice 
filter (?c != ?p) 

#use the values keyword to filter on 
VALUES (?filter) {
